export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_GETALL_REQUEST = "USER_GETALL_REQUEST";
export const USER_GETALL_SUCCESS = "USER_GETALL_SUCCESS";
export const USER_GETALL_FAIL = "USER_GETALL_FAIL";

export const USER_GETONE_REQUEST = "USER_GETONE_REQUEST";
export const USER_GETONE_SUCCESS = "USER_GETONE_SUCCESS";
export const USER_GETONE_FAIL = "USER_GETONE_FAIL";

export const MOVIE_ADD_REQUEST = "MOVIE_ADD_REQUEST";
export const MOVIE_ADD_SUCCESS = "MOVIE_ADD_SUCCESS";
export const MOVIE_ADD_FAIL = "MOVIE_ADD_FAIL";

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_FAIL = "MOVIE_DELETE_FAIL";
